version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_ROOT_PASSWORD: M4r1aDb